In [3]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [1]:
!wget -O drugs.csv 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv'

--2024-07-26 23:06:49--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.45.118.108
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.45.118.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5827 (5.7K) [text/csv]
Saving to: ‘drugs.csv’

drugs.csv           100%[===================>]   5.69K  --.-KB/s    in 0s      

2024-07-26 23:06:50 (1.82 GB/s) - ‘drugs.csv’ saved [5827/5827]



In [149]:
df = pd.read_csv('drugs.csv')
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [12]:
df.shape

(200, 6)

In [13]:
df.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [131]:
x = np.asarray(df[['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']])
x[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.114],
       [28, 'F', 'NORMAL', 'HIGH', 7.798],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [132]:
from sklearn import preprocessing

#convertendo as labels categóricas

converting_label_sex = preprocessing.LabelEncoder()
converting_label_sex.fit(['F', 'M'])
x[:,1] = converting_label_sex.transform(x[:,1])

converting_label_bp = preprocessing.LabelEncoder()
converting_label_bp.fit(['LOW', 'NORMAL', 'HIGH'])
x[:,2] = converting_label_bp.transform(x[:,2])

converting_label_cholesterol = preprocessing.LabelEncoder()
converting_label_cholesterol.fit(['NORMAL', 'HIGH'])
x[:,3] = converting_label_cholesterol.transform(x[:,3])

x[:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [151]:
x[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [150]:
y = df['Drug']
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [152]:
from sklearn.model_selection import train_test_split
#separando aleatoriamente os sets de treinamento e teste

train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3, random_state=4)


In [153]:
train_y

77     drugY
127    drugX
5      drugX
118    drugA
113    drugX
       ...  
104    drugY
129    drugX
183    drugY
174    drugA
122    drugY
Name: Drug, Length: 140, dtype: object

In [154]:
print(train_y.shape)
print(train_x.shape)

(140,)
(140, 5)


In [155]:
print(test_y.shape)
print(test_x.shape)

(60,)
(60, 5)


In [156]:
dec_tree = DecisionTreeClassifier(criterion = 'entropy', max_depth=4)
dec_tree

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [157]:
dec_tree.fit(train_x, train_y)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [158]:
prediction = dec_tree.predict(test_x)

In [159]:
print(prediction [0:10])
print(test_y[0:10])

['drugY' 'drugY' 'drugY' 'drugY' 'drugC' 'drugX' 'drugY' 'drugY' 'drugY'
 'drugA']
11     drugY
99     drugY
128    drugY
175    drugY
1      drugC
111    drugX
90     drugY
177    drugY
88     drugY
187    drugA
Name: Drug, dtype: object


In [163]:
from sklearn import metrics
import matplotlib.pyplot as plt

print("Acurácia: ", metrics.accuracy_score(test_y, prediction))
#Resultado estranho quando eu tranformava y em uma np.array, a acurácia girava em torno de 0.3~0.4

Acurácia:  0.9666666666666667


In [167]:
!conda install -c conda-forge pydotplus -y
!conda install -c conda-forge python-graphviz -y

/bin/bash: line 1: conda: command not found
/bin/bash: line 1: conda: command not found


In [169]:
from io import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn import tree

#código do github para printar a decision tree


dot_data = StringIO()
filename = "drugtree.png"
featureNames = df.columns[0:5]
out=tree.export_graphviz(dec_tree,feature_names=featureNames, out_file=dot_data, class_names= np.unique(train_y), filled=True,  special_characters=True,rotate=False)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png(filename)
img = mpimg.imread(filename)
plt.figure(figsize=(100, 200))
plt.imshow(img,interpolation='nearest')